name: Command via SSH

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: garygrossgarten/github-action-ssh@test/0.4.0
        with:
          command: node fail.js 
          host: ${{ secrets.HOST }}
          username: garygrossgarten
          passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.PRIVATE_KEY}}

        env:
          CI: true
